services:
  mui:
    build: social-api-frontend/.
    ports:
      - "3001:3000"
    container_name: mui-frontend
    depends_on:
      - api
  icds-frontend:
    build: icds-frontend/.
    ports:
      - "3000:3000"
    container_name: icds-frontend
    depends_on:
      - api
  api:
    build: newApi/.
    ports:
      - "3101:3101"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://mongo:27017/newapi
      - NODE_OPTIONS=--max_old_space_size=8192
  db:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: