services:
  mui:
    image: ghcr.io/nmcc1212/mui-frontend
    ports:
      - "3001:3000"
    container_name: mui-frontend
    depends_on:
      - api
  icds-frontend:
    image: ghcr.io/nmcc1212/icds-frontend
    ports:
      - "3000:3000"
    container_name: icds-frontend
    depends_on:
      - api
  api:
    image: ghcr.io/nmcc1212/social-api
    container_name: api
    ports:
      - "3101:3101"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://mongo:27017/newapi
      - NODE_OPTIONS=--max_old_space_size=8192
  db:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./mongo/socialAPI.posts.json:/docker-entrypoint-initdb.d/socialAPI.posts.json:ro
      - ./mongo/socialAPI.users.json:/docker-entrypoint-initdb.d/socialAPI.users.json:ro

volumes:
  mongo-data: