name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: nmcc1212
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./newAPI/.
          platforms: linux/amd64,linux/arm64
          file: newAPI/Dockerfile
          push: true
          tags: ghcr.io/nmcc1212/social-api:latest

  build-icds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: nmcc1212
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./icds-frontend/.
          platforms: linux/amd64,linux/arm64
          file: icds-frontend/Dockerfile
          push: true
          tags: ghcr.io/nmcc1212/icds-frontend:latest

  build-mui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: nmcc1212
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./social-api-frontend/.
          platforms: linux/amd64,linux/arm64
          file: social-api-frontend/Dockerfile
          push: true
          tags: ghcr.io/nmcc1212/mui-frontend:latest
