name: Jest API Tests + SonarQube Scan
on:
  push:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        working-directory: newAPI
        run: npm ci
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-container-name: db
      - name: Install mongosh
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh mongodb-org-tools
      - name: Load posts into MongoDB
        run: mongoimport --uri mongodb://localhost:27017/socialAPI --collection posts --file ./mongo/socialAPI.posts.json --jsonArray
      - name: Load users into MongoDB
        run: mongoimport --uri mongodb://localhost:27017/socialAPI --collection users --file ./mongo/socialAPI.users.json --jsonArray
      - name: Run Jest API tests
        working-directory: newAPI
        run: npm run test
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
