name: Jest API Tests
on:
  push:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        working-directory: newAPI
        run: npm ci
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: latest
          mongodb-db: socialAPI
      - name: Run API
        working-directory: newAPI
        run: npm run dev & 
      - name: Wait for API to start
        run: sleep 10
      - name: Run Jest API tests
        working-directory: newAPI
        run: npm run test
