name: Lint ICDS, MUI and API
on:
  push:
    branches: [main]

jobs:
  lint-icds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: "21"
      - name: Install dependencies
        working-directory: icds-frontend
        run: |
          npm ci
          npm install @microsoft/eslint-formatter-sarif
      - name: Lint
        working-directory: icds-frontend
        run: npx next lint --format @microsoft/eslint-formatter-sarif --output-file eslint-icds.sarif
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./icds-frontend/eslint-icds.sarif
  lint-mui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: "21"
      - name: Install dependencies
        working-directory: social-api-frontend
        run: |
          npm ci
          npm install @microsoft/eslint-formatter-sarif
      - name: Lint
        working-directory: social-api-frontend
        run: npx next lint --format @microsoft/eslint-formatter-sarif --output-file eslint-mui.sarif
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./social-api-frontend/eslint-mui.sarif
  lint-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: "21"
      - name: Install dependencies
        working-directory: newAPI
        run: |
          npm ci
          npm install @microsoft/eslint-formatter-sarif
      - name: Lint
        working-directory: newAPI
        run: npx eslint . --format @microsoft/eslint-formatter-sarif --output-file eslint-api.sarif
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./newAPI/eslint-api.sarif
