name: OSV-Scanner

on:
  push:
    branches: [main]

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  scan-api:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v1.7.3"
    with:
      scan-args: "./newAPI"
      results-file-name: "api-osv-results.sarif"
      upload-sarif: true
  scan-icds:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v1.7.3"
    with:
      scan-args: "./icds-frontend"
      results-file-name: "icds-osv-results.sarif"
      upload-sarif: true
  scan-mui:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v1.7.3"
    with:
      scan-args: "./social-api-frontend"
      results-file-name: "mui-osv-results.sarif"
      upload-sarif: true
