name: OSV-Scanner

on:
  push:
    branches: [main]

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  scan:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v1.7.3"
    with:
      scan-args: "-r"
      upload-sarif: true
