name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        working-directory: icds-frontend
        run: npm ci
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-container-name: db
      - name: Install mongosh
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh mongodb-org-tools
      - name: Load posts into MongoDB
        run: mongoimport --uri mongodb://localhost:27017/socialAPI --collection posts --file ./mongo/socialAPI.posts.json --jsonArray
      - name: Load users into MongoDB
        run: mongoimport --uri mongodb://localhost:27017/socialAPI --collection users --file ./mongo/socialAPI.users.json --jsonArray
      - name: Start the API
        run: docker compose -f docker/docker-compose-nodep.yml up -d api icds-frontend
      - name: Install Playwright Browsers
        working-directory: icds-frontend
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: icds-frontend
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
